vault_address: https://guttu.cyware.io:8200
servers:
- ip: 1.0.0.2
  server_name: Csap Staging Server
  login_username: ubuntu
  vault_role: csap-staging-bastia-role
- ip: 1.0.0.1
  server_name: Csap Production Server
  login_username: ubuntu
  vault_role: csap-staging-bastia-role
- ip: 1.3.0.1
  server_name: CTIX Production Server
  login_username: ubuntu
  vault_role: csap-staging-bastia-role

