vault_address: https://guttu.cyware.io:8200
servers:
- ip: 1.0.0.2
  server_name: Csap Staging Server
- ip: 1.0.0.1
  server_name: Csap Production Server
- ip: 1.3.0.1
  server_name: CTIX Production Server
